---
title: "Portafolio 1_Topología"
author: "Elvis Mauricio Sánchez Rogel"
date: "Curso de Topología_primer año"
output: 
  pdf_document: 
    keep_tex: yes
    number_sections: yes
    toc: yes
    toc_depth: 2
    latex_engine: xelatex
  html_document:
    keep_tex: true
    number_sections: yes
    toc: yes
    toc_depth: 2
  word_document:
    keep_tex: true
    toc: yes
    toc_depth: '2'
toccolor: blue  
header-includes: \usepackage{amsmath,amssymb,amsfonts,longtable,mathtools,color,array,booktabs,algorithm2e} 
                 \newcommand\red[1]{\textcolor{red}{#1}}  
                 \newcommand\blue[1]{\textcolor{blue}{#1}}     
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#  Portafolio 1
## Ejercicio 1 (1.5 pts)
\textcolor{red}{Sea $d$ una distancia definida en un conjunto arbitrario $X$, sea $k \in \mathbb{R}$.Estudiar para que valores de $k$ la aplicación $d'$ definida como $d'(x,y)=d(x,y)+k$ sería también una métrica.}


\textbf{Demostración:}

Claramente hay que comprobar que se cumpla la primera condición de métrica. Para que $d'(x,x)=d(x,x)+k$ sea métrica debe de cumplirse que la distancia $d(x,x)=0$ para todo $x \in X$, Es decir::
\begin{eqnarray*}
  0 & = & d'(x,x) \\
  0 & = & d(x,x)+k  \\
  0 & = & 0 + k \\
  0 & = & k 
\end{eqnarray*}
Por tanto, el único valor $k$ para que $d'(x,y) =d(x,y)+k$ se una métrica es que sea $k=0$.

## Ejercicio 2 (1.5 pts)

\textcolor{red}{ Sea $(X,d)$ un espacio métrico. Probar que las bolas cerradas son conjuntos cerrados.}

\textbf{Demostración:}

Sea $\hat{x} \in X$ y $r>0$, entonces $\overline{B}(\hat{x},r)=\{ \hat{y} \in X \mid  d(\hat{y},\hat{x}) \leq r\}$ es un conjunto cerrado, pués
$X \setminus \overline B(\hat{x},r) =  \{ \hat{y} \in X \mid d(\hat{y},\hat{x}) > r\}= A$ es un conjunto abierto. 

Para ello demostraremos $X \setminus \overline B(\hat{x},r)= \{ \hat{y} \in X \mid d(\hat{y},\hat{x}) > r\}= A$ es un abierto.

Sea $\hat{y} \in A$, entonces $d(\hat{y},\hat{x})>r$, y sea $\epsilon=d(d\hat{x},\hat{y})-r>0$, tomamemos un $\hat{z} \in B(\hat{y}, \epsilon)$, tal que se tiene lo siguiente:
\begin{eqnarray*}
                           d(\hat{y},\hat{x}) & \leq & d(\hat{y},\hat{z}) + d(\hat{z},\hat{x})\\
        d(\hat{y},\hat{x}) +r - d(\hat{y},\hat{x}) < d(\hat{y},\hat{x}) - d(\hat{y},\hat{z}) & \leq & d(\hat{z},\hat{x})\\
                                              r & < & d(\hat{z},\hat{x})\\
\end{eqnarray*}
Por lo tanto, $\hat{z} \in A$, esto prueba  $B(\hat{y}, \epsilon) \subset A$, por lo tanto $A$ es un conjunto abierto, probando así que $\overline B(\hat{x},r)$ es cerrado.

## Ejercicio 3 (1.5 pts)

\textcolor{red}{Sea $X$ un conjunto  y $p \in X$ un punto arbitrario. Demostrar que la familia $\tau_p = \{ U \subset X \;|\; p \in U \} \cup \{ \varnothing \}$ es una topología}

\textbf{Demostración:}

Claramente se observa que el vacío forma parte $\varnothing \in \tau_p$. Por otro  lado, $p \in X$, en consecuencia $X \in \tau_p$.

Sea $\{U_j \}_{j \in I} \subset \tau_p$, si $U_j= \varnothing$ para todo $j \in I$, entonces $\displaystyle \bigcup_{j \in J} U_j  = \varnothing$, en consecuencia $\displaystyle\bigcup_{j \in J} U_j \in \tau_p$. Por otro lado, si existe $U_i \neq \varnothing$, entonces $p \in U_i$, en consecuencia $p\in \displaystyle\bigcup_{j \in J} U_j$, por lo tanto $\displaystyle\bigcup_{j \in J} U_j \in \tau_p$.

Ahora sea $\{U_j\}_{j=1}^k\subseteq \tau_p$, si para algún $i\in \{1,\ldots, k\}$ sucede que $U_i=\emptyset$, entonces $\displaystyle\bigcap_{j=1}^k U_j=\emptyset$, por tanto $\displaystyle\bigcap_{j=1}^k U_j\in \tau_p$. Por otro lado si sucede que $U_j\ne \emptyset$ para todo  $j\in \{1,\ldots, k\}$, se tiene que $p\in U_j$ para todo  $j\in \{1,\ldots, k\}$, así que $p\in \displaystyle\bigcap_{j=1}^k U_j$, por lo tanto $\displaystyle\bigcap_{j=1}^k U_j\in \tau_p$.

## Ejercicio 4 (2 pts)

\textcolor{red}{Se considera el conjunto $X=\{a,b,c,d,e,f \}$. Indicar justificadamente si las siguientes familias constituyen topologías en $X$.}
\begin{itemize}
\item [a)] $\tau_{1} =\{ \varnothing,X,\{a\},\{c,d\},\{a,c,d\},\{a,b,c,d,e\}\}$
\item [b)] $\tau_{2} =\{ \varnothing,X,\{a\},\{c,d\},\{a,c,e\},\{b,c,d\},\{a,b,c,d,e\}\}$
\item [c)] $\tau_{3} =\{ \varnothing,X,\{a\},\{f\},\{a,f\},\{a,c,f\},\{b,c,d,e,f\}\}$
\item [d)]$\tau_{4} =\{ \varnothing,X,\{b\},\{d\},\{a,d\},\{a,b,d\},\{a,b,c,d,e\}\}$
\end{itemize}
\textcolor{blue}{a) $\tau_{1} =\{ \varnothing,X,\{a\},\{c,d\},\{a,c,d\},\{a,b,c,d,e\}\}$}

\textbf{Demostración:}

Claramente el vacio $\varnothing$ y el $X$ estan en la topología $\tau_1$.

Por otro lado, las uniones e interseciones:

\begin{align*}
\mbox{Unión}                               &        &          &\mbox{Intersección} \\
\{a\} \cup \varnothing =\{a\}              &        &          &\{a\} \cap \{c,d\}=\varnothing \\
\{a\} \cup \{c,d\}=\{a,c,d\}               &        &          &\{a\} \cap \{a,c,d\}=\{a\} \\
\{a\} \cup \{a,c,d\}=\{a,c,d\}             &        &          &\{a\} \cap \{a,b,c,d,e\}=\{a\} \\
\{c,d\} \cup \{a,c,d\}=\{a,c,d\}           &        &          &\{c,d\} \cap \{a,c,d\}=\{c,d\} \\
\{a,c,d\} \cup \{a,b,c,d,e\}=\{a,b,c,d,e\} &        &          &\{a,c,d\} \cap \{a,b,c,d,e\}=\{a,c,d\} \\
\{a,b,c,d,e\} \cup \{a,b,c,d,e,f\}= X      &        &          &\{a,b,c,d,e\} \cap \{a,b,c,d,e,f\}=\{a,b,c,d,e\} 
\end{align*}

las uniones y las intersecciones de los subconjuntos estan en la topología $\tau_{1}$. Por lo tanto $\tau_{1}$ es una topología sobre $X$

\textcolor{blue}{b) $\tau_{2} =\{ \varnothing,X,\{a\},\{c,d\},\{a,c,e\},\{b,c,d\},\{a,b,c,d,e\}\}$}

\textbf{Demostración:}

Claramente el vacio $\varnothing$ y el $X$ estan en la topología $\tau_2$.

Por otro lado, las uniones e interseciones:

\begin{align*}
\mbox{Unión}                               &        &          &\mbox{Intersección} \\
\{a\} \cup \varnothing =\{a\}              &        &          &\{a\} \cap \{c,d\}=\varnothing \\
\{a\} \cup \{c,d\}=\{a,c,d\}               &        &          &\{a\} \cap \{a,c,e\}=\{a\} \\
\{a\} \cup \{a,c,d\}=\{a,c,d\}             &        &          &\{a\} \cap \{b,c,d\}=\varnothing \\
\{c,d\} \cup \{a,c,d\}=\{a,c,d\}           &        &          &\textcolor{blue}{\{c,d\} \cap \{a,c,e\}=\{c\}} \\
\{a,c,d\} \cup \{a,b,c,d,e\}=\{a,b,c,d,e\} &        &          &\{a,c,e\} \cap \{b,c,d\}=\{c\} \\
\{a,b,c,d,e\} \cup \{a,b,c,d,e,f\}= X      &        &          &\{b,c,d\} \cap \{a,b,c,d,e,f\}=\{b,c,d\} 
\end{align*}

Como  $\{c,d\} \cap \{a,c,e\}=\{c\} \notin \tau_2$. Por lo tanto $\tau_{2}$ no es una topología sobre $X$

\textcolor{blue}{c) $\tau_{3} =\{ \varnothing,X,\{a\},\{f\},\{a,f\},\{a,c,f\},\{b,c,d,e,f\}\}$}

\textbf{Demostración:}

Claramente el vacio $\varnothing$ y el $X$ estan en la topología $\tau_3$.

Por otro lado, las uniones e interseciones:

\begin{align*}
\mbox{Unión}                               &        &          &\mbox{Intersección} \\
\{a\} \cup \varnothing =\{a\}              &        &          &\{a\} \cap \{f\}=\varnothing \\
\{a\} \cup \{f\}=\{a,f\}                   &        &          &\{a\} \cap \{a,f\}=\{a\} \\
\{a\} \cup \{a,c,f\}=\{a,c,f\}             &        &          &\{a\} \cap \{b,c,d,e,f\}=\varnothing \\
\{a\} \cup \{b,c,d,e,f\}= X                &        &          &\{f\} \cap \{a,f\}=\{f\} \\
\{a,f\} \cup \{a,c,f\}=\{a,c,f\}           &        &          &\{a,f\} \cap \{a,c,f\}=\{a,f\} \\
\{a,c,f\} \cup \{b,c,d,e,f\}= X            &        &          &\textcolor{blue}{\{a,c,f\} \cap \{b,c,d,e,f\}=\{c,f\}}
\end{align*}

Como  $\{a,c,f\} \cap \{b,c,d,e,f\}=\{c,f\} \notin \tau_3$. Por lo tanto $\tau_{3}$ no es una topología sobre $X$

\textcolor{blue}{d) $\tau_{4} =\{ \varnothing,X,\{b\},\{d\},\{a,d\},\{a,b,d\},\{a,b,c,d,e\}\}$}

\textbf{Demostración:}

Claramente el vacio $\varnothing$ y el $X$ estan en la topología $\tau_4$.

Por otro lado, las uniones e interseciones:

\begin{align*}
\mbox{Unión}                                  &        &          &\mbox{Intersección} \\
\{b\} \cup \varnothing =\{b\}                 &        &          &\{b\} \cap \{d\}=\varnothing \\
\{b\} \cup \{a,d\}=\{a,b,d\}                  &        &          &\{d\} \cap \{a,d\}=\{d\} \\
\textcolor{blue}{\{b\} \cup \{d\}=\{b,d\}}                      &        &          &\{a,d\} \cap \{a,b,d\}=\{a,d\} \\
\{a,d\} \cup \{a,b,d\}= \{a,b,d\}             &        &          &\{a,d\} \cap \{d\}=\{d\} \\
\{a,b,d\} \cup \{a,b,c,d,e\}=\{a,b,c,d,e\}    &        &          &\{a,f\} \cap \{a,c,f\}=\{a,f\} \\
\{a,d\} \cup X = X                            &        &          &\{a,b,d\} \cap \{a,b,c,d,e\}=\{a,b,d\} 
\end{align*}

Como  $\{b\} \cup \{d\}=\{b,d\} \notin \tau_4$. Por lo tanto $\tau_{4}$ no es una topología sobre $X$.

## Ejercico 5 (1.5 pts)

\textcolor{red}{Probar que el conjunto $\mathcal{B}=\{(a,\infty), a \in \mathbb{R}\}$ es una base de topología en $\mathbb{R}$. La topología generada por cada base se llama topología de Kolmogorov.}

Sea $x \in \mathbb{R}$,entonces existe $x \in B_o=(a, \infty)$, con $B_o=\{ y \in \mathbb{R} \mid y > a\}$, tal que $B_o \in  \mathcal{B}$, cumpliendo así, la primera condición.

Sean $B_1,B_2 \in \mathcal{B}$, entonces $B_1=(a_1, \infty)$ y $B_2=(a_2, \infty)$, con $a,b \in \mathbb{R}$, si tomamos $a=max(a_1,a_2)$, tal que se cumple $B_1 \cap B_2=(a, \infty)$, entonces existe $B_3=(a,\infty) \in \mathcal{B}$, en consecuencia $x\in B_3 \subset B_1 \cap B2$. Por lo tanto, se ha comprobado la segunda condición.

## Ejercicio 6 (2pts)

\textcolor{red}{Considera $X=\mathbb{R}$. Indicar si los siguientes conjuntos son abiertos y/o cerrados considerando la topología usual $\tau_u$ y la topología de Kolmogorov $\tau_K$ descrita en el ejemplo anterior.}
\begin{itemize}
\item[a)] $(0,1)$
El intervalo $(0,1)$ es abierto en la $\tau_u$, debido a que su complemeto es cerrado es decir, $(-\infty,0]U[1,\infty)$.

Por otro lado, no es abierto, ni cerrado en la topología de Kolmogorov, debido a que falla en el $1$ por la definición de baseen $\tau_k$, y no es cerrado ya su complemento sería $(-\infty,0]U[1,\infty)$, ninguno se ajusta a los básicos de la forma $(a,\infty)$.

\item[b)] $(0,1]$
El intervalo $(0,1]$ es cerrado en la $\tau_u$, debido a que su complemento es abierto $(1,\infty)$.
No es abierto, ni cerrado en $\tau_k$, porque no hay básico en su complemento de la forma $(a, \infty)$.
\item[c)] $[0,1]$
El intervalo $[0,1]$ es cerrado en la $\tau_u$, debido a que su complemento es abierto $(-\infty, 0) \cup (1,\infty)$

Por otro lado, no es abierto ni cerrado en la topología de Kolmogorov, devido a que falla en el $0$ y $1$ por la definición de base  en $\tau_k$.porque no hay básico en su complemento de la forma $(a, \infty)$.

\item[d)] $[1, \infty)$
El intervalo $[1, \infty)$ no es abierto en la $\tau_u$, pero si cerrado $\tau_u$, debido a que su complemento es abierto $(-\infty,1)$.

Por otro lado, no es abierto en la topología de Kolmogorov, devido a que falla en el $1$ por la definición de base  en $\tau_k$.
No es cerrado en $\tau_k$, porque no hay basico en su complemento de la forma $(a, \infty)$.

\item[e)] $(- \infty,0]$
El intervalo $(- \infty,0]$ no es abierto en la $\tau_u$, pero si cerrado $\tau_u$, debido a que su complemento es abierto $(0,\infty)$.
Mientras que no es abierto en la topología de Kolmogorov, devido a que falla en el $0$ por la definición de base  en $\tau_k$.
Por otro lado, si es cerrado en $\tau_k$, ya que su complemento es abierto, es decir, $(0,\infty)$ es abierto.
\end{itemize}

## Ejemplo de metricas

Sea $X$ un conjunto no vacio y $d: X \times X \longrightarrow \mathbb{R}$ una función que satisface lo siguiente:
\begin{itemize}
\item [a)] $d(x,y)=0$, si y solo si $x=y$
\item [b)] $d(x,y)= d(x,z)+d(y,z)$
\end{itemize}
Probar que es métrica

\textbf{Demostración:}

Sabemos de la primera condición, $d(x,y)=0$, si y solo si $x=y$.

Por otro lado, comprobaremos la segunda condición de simetría, para ello tenemos:

Sea $z=x \in X$, entonces:
\begin{eqnarray*}
d(x,y) \leq  d(x,z) + d(y,z)\\
d(x,y) \leq  d(x,x) + d(y,x)\\
d(x,y) \leq  d(y,x)
\end{eqnarray*}
Ahora si $y=z$
\begin{eqnarray*}
d(y,x) \leq  d(y,z) + d(x,z)\\
d(y,x) \leq  d(y,y) + d(x,y)\\
d(y,x) \leq  d(x,y)
\end{eqnarray*}
Por lo tanto, $d(x,y) \leq d(y,x) \leq d(x,y)$, entonces $d(x,y)= d(y,x)$.

Finalmente, la propiedad de la desigualdad del triángulo, se cumple por la condición de simetría de la prueba anterior
\begin{eqnarray*}
d(x,y) \leq  d(x,z) + d(y,z)=d(z,y)\\
d(x,y) \leq  d(x,z) + d(z,y)
\end{eqnarray*}
Por lo tanto, se cumple la desigualdad del triángulo pedida.

## Sea $(X,d)$ un espacio métrico. Probar que 
$\alpha (x,y)=min \{1,d(x,y)\}$; $\beta (x,y)= \frac{d(x,y)}{1+d(x,y)}$
son métricas en X.

\textbf{Demostración:}

Como sabemos el menor valor de distancia que la métrica $d(x,y)$ puede tomar es cero, si y solo $x=y$. Claramente
$\alpha (x,y)=d(x,y)$, cumpliendose así todas las condiciones de métrica. Por lo tanto $\alpha (x,y)$
es una métrica sobre X.

En el caso de $\beta (x,y)= \frac{d(x,y)}{1+d(x,y)}$, es una métrica

\textbf{Demostración:}

Notemos si $\beta (x,y)=0$, tenemos
\begin{eqnarray*}
0 & = & \frac{d(x,y)}{1+d(x,y)}\\
0 & = & d(x,y)\\
\end{eqnarray*}
como $d(x,y)=0$ y es métrica, entonces $\beta (x,y)=0$, la primera condición se cumple.

Notemos que si $d(x,y)=d(y,x)$, entonces
\begin{eqnarray*}
\frac{d(x,y)}{1+d(x,y)} & = & \frac{d(y,x)}{1+d(y,x)}\\
\end{eqnarray*}
La cmoida 
$45 \mid$

¡Hasta aqui me quede!
Elvis Sanchez Rogellll
0996211676
$\alpha$
 Así tenemos que la tutoría significa grandes avances en la matemática

https://math.stackexchange.com/questions/3847448/proof-that-the-kolmogorov-topology-is-indeed-a-topology-over-mathbbr
